name = "madmedcheck"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "madmedcheck-db"
database_id = "9f2b717c-47a7-4066-9a53-87ad3b5f1758"
