name = "madmedcheck"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[vars]
name = "madmedcheck"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "52329880-9653-45a4-bf4d-37c908cdcfdb"
database_id = ""


